<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */
$config['query_string_segment'] = 'start';
$config['full_tag_open'] = '<div aria-label="Page navigation" class="col-md-12 col-xs-12 main-pag" ><ul class="pagination">';
$config['full_tag_close'] = '</ul></div>';

$config['first_link'] = '<span aria-hidden="true"><i class="zmdi zmdi-chevron-left"></i><i class="zmdi zmdi-chevron-left"></i></span>';
$config['first_tag_open'] = '<li>';
$config['first_tag_close'] = '</li>';

$config['last_link'] = '<span aria-hidden="true"><i class="zmdi zmdi-chevron-right"></i><i class="zmdi zmdi-chevron-right"></i></span>';
$config['last_tag_open'] = '<li>';
$config['last_tag_close'] = '</li>';

$config['next_link'] = '<span aria-hidden="true"><i class="zmdi zmdi-chevron-right"></i></span>';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';

$config['prev_link'] = '<span aria-hidden="true"><i class="zmdi zmdi-chevron-left"></i></span>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';

$config['cur_tag_open'] = '<li class="pag-active"><a>';
$config['cur_tag_close'] = '</a></li>';

$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-27 14:08:27 */
/* http://harviacode.com */